### ISSUE TITLE
download script for the dataset

### ISSUE THREAD

**Issue by nocotan** [st-tech/zozo-shift15m#152]
e.g.

- scripts/download_all.sh
- scripts/download_jsonl.sh
- scripts/download_task1.sh
- scripts/download_task2.sh
- scripts/downlaod_cnn_features.sh

**Comment by wildsnowman** [comment]
ok!

**Comment by wildsnowman** [comment]
please note that the label data is a json file

**Comment by wildsnowman** [comment]
created bash files

**Comment by wildsnowman** [comment]
usage:
bash scripts/download_all.sh
