### ISSUE TITLE
Got an TypeError exception when try to run item category prediction task

### ISSUE THREAD

**Issue by you0xy** [st-tech/zozo-shift15m#180]
Thank you for your great work and dataset opening at first.

**Description**
When I tried to run the item_category_prediction task following the usage[item_category_prediction](https://github.com/st-tech/zozo-shift15m/tree/main/benchmarks/item_category_prediction#run)
I got an exception like this:

![itemcategoryPoetry](https://user-images.githubusercontent.com/82438883/141415873-92811451-bddd-4ed1-a225-6238a4935e17.jpg)

**Environment:**
 - Python 3.8.8

It will be so helpful if you can give any gracious advice, thank you.

**Comment by nocotan** [comment]
@you0xy Thank you for your report.
In response to your issue, we have updated the main branch.
Please try again after ```git pull``` the latest version of the source code.
